// <auto-generated />
using System;
using Graff.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Graff.Migrations
{
    [DbContext(typeof(GraffContext))]
    [Migration("20190414203628_AtualizaFK")]
    partial class AtualizaFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Graff.Models.LancesLeilao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Leilaoid");

                    b.Property<int>("PessoaId");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.HasIndex("Leilaoid");

                    b.HasIndex("PessoaId");

                    b.ToTable("LancesLeilao");
                });

            modelBuilder.Entity("Graff.Models.Leilao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProdutoId");

                    b.Property<double>("valorLance");

                    b.HasKey("id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Leilao");
                });

            modelBuilder.Entity("Graff.Models.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("idade");

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Graff.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Graff.Models.LancesLeilao", b =>
                {
                    b.HasOne("Graff.Models.Leilao", "Leilao")
                        .WithMany()
                        .HasForeignKey("Leilaoid");

                    b.HasOne("Graff.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Graff.Models.Leilao", b =>
                {
                    b.HasOne("Graff.Models.Produto", "Produto")
                        .WithMany("Leiloes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
